
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: |
        docker build -t my-app:${{ github.sha }} .
      env:
        DOCKER_BUILDKIT: 1

    - name: Send notification to Google Chat
      if: always()  # Ensures this step runs even if previous steps fail
      env:
        GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-Type: application/json' \
        -d '{
        "text": "Github-actionsDeployment Started\nJob: student-node\nEnvironment: Development\nBranch: '${{ github.ref_name }}'\nCommited-By: '${{ github.actor }}'\nCommited-Message: '${{ github.event.head_commit.message }}'"
        }' $GOOGLE_CHAT_WEBHOOK_URL
        
    - name: Set start time
      id: start_time
      run: echo "::set-output name=timestamp::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

    - name: Set end time
      id: end_time
      run: echo "::set-output name=timestamp::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
