name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: |
        docker build -t my-app:${{ github.sha }} .
      env:
        DOCKER_BUILDKIT: 1

    - name: Set start time
      id: start_time
      run: echo "START_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

    - name: Set end time
      id: end_time
      run: echo "END_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

    - name: Send notification to Google Chat
      env:
        GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        START_TIME: ${{ env.START_TIME }}
        END_TIME: ${{ env.END_TIME }}
      if: always()
      run: |
        curl -X POST -H 'Content-Type: application/json' \
          -d '{
                "text": "Deployment Notification\n\n
                        **Job:** ${GITHUB_JOB}\n
                        **Repo:** ${GITHUB_REPOSITORY}\n
                        **Branch:** ${GITHUB_REF}\n
                        **Committed By:** ${GITHUB_ACTOR}\n
                        **Commit Message:** ${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}\n
                        **Deployment Start Time:** ${START_TIME}\n
                        **Deployment End Time:** ${END_TIME}"
              }' \
          $GOOGLE_CHAT_WEBHOOK
