name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: |
        docker build -t my-app:${{ github.sha }} .
      env:
        DOCKER_BUILDKIT: 1

    - name: Set start time
      id: start_time
      run: echo "start_time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

    - name: Set end time
      id: end_time
      run: echo "end_time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

    - name: Send notification to Google Chat
      env:
        GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
      if: always()
      run: |
        MESSAGE="Build and deploy completed successfully! The application is running at http://localhost:9090/hello"
        curl -X POST -H 'Content-Type: application/json' \
        -d "{\"text\": \"${MESSAGE}\"}" \
        $GOOGLE_CHAT_WEBHOOK
        